# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'task1.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1219, 846)
        self.video_frame = QLabel(Form)
        self.video_frame.setObjectName(u"video_frame")
        self.video_frame.setGeometry(QRect(50, 40, 561, 371))
        self.Screen_shot = QLabel(Form)
        self.Screen_shot.setObjectName(u"Screen_shot")
        self.Screen_shot.setGeometry(QRect(670, 50, 431, 381))
        self.screen_button = QPushButton(Form)
        self.screen_button.setObjectName(u"screen_button")
        self.screen_button.setGeometry(QRect(250, 440, 221, 51))
        font = QFont()
        font.setPointSize(10)
        self.screen_button.setFont(font)
        self.map_label = QLabel(Form)
        self.map_label.setObjectName(u"map_label")
        self.map_label.setGeometry(QRect(550, 400, 641, 421))
        self.map_label.setPixmap(QPixmap(u"../../../../OneDrive/Desktop/WhatsApp Image 2023-12-16 at 18.59.14_aaf0464e.jpg"))
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 540, 61, 51))
        font1 = QFont()
        font1.setPointSize(12)
        self.label_2.setFont(font1)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(180, 540, 61, 51))
        self.label_3.setFont(font1)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(320, 540, 61, 51))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(450, 540, 61, 51))
        self.label_5.setFont(font1)
        self.Is1 = QPushButton(Form)
        self.Is1.setObjectName(u"Is1")
        self.Is1.setGeometry(QRect(20, 630, 41, 31))
        self.Ds1 = QPushButton(Form)
        self.Ds1.setObjectName(u"Ds1")
        self.Ds1.setGeometry(QRect(20, 680, 41, 31))
        self.Is_label1 = QLabel(Form)
        self.Is_label1.setObjectName(u"Is_label1")
        self.Is_label1.setGeometry(QRect(70, 635, 31, 21))
        self.Ds_label1 = QLabel(Form)
        self.Ds_label1.setObjectName(u"Ds_label1")
        self.Ds_label1.setGeometry(QRect(70, 680, 31, 21))
        self.line = QFrame(Form)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(130, 530, 20, 311))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.Ds_label2 = QLabel(Form)
        self.Ds_label2.setObjectName(u"Ds_label2")
        self.Ds_label2.setGeometry(QRect(220, 680, 31, 21))
        self.Ds2 = QPushButton(Form)
        self.Ds2.setObjectName(u"Ds2")
        self.Ds2.setGeometry(QRect(170, 680, 41, 31))
        self.Is_label2 = QLabel(Form)
        self.Is_label2.setObjectName(u"Is_label2")
        self.Is_label2.setGeometry(QRect(220, 635, 31, 21))
        self.Is2 = QPushButton(Form)
        self.Is2.setObjectName(u"Is2")
        self.Is2.setGeometry(QRect(170, 630, 41, 31))
        self.line_2 = QFrame(Form)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(280, 530, 20, 311))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.Ds3 = QPushButton(Form)
        self.Ds3.setObjectName(u"Ds3")
        self.Ds3.setGeometry(QRect(310, 680, 41, 31))
        self.Is_label3 = QLabel(Form)
        self.Is_label3.setObjectName(u"Is_label3")
        self.Is_label3.setGeometry(QRect(360, 635, 31, 21))
        self.Ds_label3 = QLabel(Form)
        self.Ds_label3.setObjectName(u"Ds_label3")
        self.Ds_label3.setGeometry(QRect(360, 680, 31, 21))
        self.Is3 = QPushButton(Form)
        self.Is3.setObjectName(u"Is3")
        self.Is3.setGeometry(QRect(310, 630, 41, 31))
        self.line_3 = QFrame(Form)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(420, 530, 20, 311))
        self.line_3.setFrameShape(QFrame.VLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.Ds4 = QPushButton(Form)
        self.Ds4.setObjectName(u"Ds4")
        self.Ds4.setGeometry(QRect(450, 680, 41, 31))
        self.Is_label4 = QLabel(Form)
        self.Is_label4.setObjectName(u"Is_label4")
        self.Is_label4.setGeometry(QRect(500, 630, 31, 21))
        self.Ds_label4 = QLabel(Form)
        self.Ds_label4.setObjectName(u"Ds_label4")
        self.Ds_label4.setGeometry(QRect(500, 690, 31, 21))
        self.Is4 = QPushButton(Form)
        self.Is4.setObjectName(u"Is4")
        self.Is4.setGeometry(QRect(450, 630, 41, 31))
        self.line_5 = QFrame(Form)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 520, 541, 20))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.line_6 = QFrame(Form)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(20, 600, 531, 16))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.cancel = QPushButton(Form)
        self.cancel.setObjectName(u"cancel")
        self.cancel.setGeometry(QRect(20, 480, 171, 31))
        self.cancel.setFont(font1)
        self.start = QPushButton(Form)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(20, 430, 171, 31))
        self.start.setFont(font1)
        self.line_4 = QFrame(Form)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(500, 530, 91, 311))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.video_frame.setText("")
        self.Screen_shot.setText("")
        self.screen_button.setText(QCoreApplication.translate("Form", u"Screenshot", None))
        self.map_label.setText("")
        self.label_2.setText(QCoreApplication.translate("Form", u"   Q1", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"   Q2", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"   Q3", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"   Q4", None))
        self.Is1.setText(QCoreApplication.translate("Form", u"I-s", None))
        self.Ds1.setText(QCoreApplication.translate("Form", u"D-S", None))
        self.Is_label1.setText(QCoreApplication.translate("Form", u": ", None))
        self.Ds_label1.setText(QCoreApplication.translate("Form", u": ", None))
        self.Ds_label2.setText(QCoreApplication.translate("Form", u": ", None))
        self.Ds2.setText(QCoreApplication.translate("Form", u"D-S", None))
        self.Is_label2.setText(QCoreApplication.translate("Form", u": ", None))
        self.Is2.setText(QCoreApplication.translate("Form", u"I-s", None))
        self.Ds3.setText(QCoreApplication.translate("Form", u"D-S", None))
        self.Is_label3.setText(QCoreApplication.translate("Form", u": ", None))
        self.Ds_label3.setText(QCoreApplication.translate("Form", u": ", None))
        self.Is3.setText(QCoreApplication.translate("Form", u"I-s", None))
        self.Ds4.setText(QCoreApplication.translate("Form", u"D-S", None))
        self.Is_label4.setText(QCoreApplication.translate("Form", u": ", None))
        self.Ds_label4.setText(QCoreApplication.translate("Form", u": ", None))
        self.Is4.setText(QCoreApplication.translate("Form", u"I-s", None))
        self.cancel.setText(QCoreApplication.translate("Form", u"Stop", None))
        self.start.setText(QCoreApplication.translate("Form", u"Start", None))
    # retranslateUi

